name: TypeScript Check

on:
  workflow_run:
    workflows: ['ESLint Check']
    types: [completed]

jobs:
  typecheck:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run typecheck
